CREATE DATABASE IF NOT EXISTS osflix;
USE osflix;

CREATE TABLE IF NOT EXISTS cache_info (
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_video INT NOT NULL,
    type VARCHAR(20) NOT NULL,
    name VARCHAR(255) NOT NULL,
    img VARCHAR(1500) NOT NULL,
    KEY id_video (id_video)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS favorites (
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_user INT NOT NULL,
    id_video INT NOT NULL,
    type VARCHAR(20) NOT NULL,
    KEY id_user (id_user)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE IF NOT EXISTS watched (
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_user INT NOT NULL DEFAULT '0',
    id_video INT NOT NULL DEFAULT '0',
    id_ep INT DEFAULT NULL,
    type VARCHAR(20) NOT NULL,
    checkpoint DOUBLE NOT NULL DEFAULT '0'
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin; 